// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPortfolioCandidate(arg1) {
  return window['go']['main']['App']['ApplyPortfolioCandidate'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CheckExternalDependencies() {
  return window['go']['main']['App']['CheckExternalDependencies']();
}

export function ClearPositionPool() {
  return window['go']['main']['App']['ClearPositionPool']();
}

export function ConfirmPositionTrades(arg1) {
  return window['go']['main']['App']['ConfirmPositionTrades'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetArenaStrategyDefinitions() {
  return window['go']['main']['App']['GetArenaStrategyDefinitions']();
}

export function GetDataUpdateStatus() {
  return window['go']['main']['App']['GetDataUpdateStatus']();
}

export function GetFactorModelRun(arg1) {
  return window['go']['main']['App']['GetFactorModelRun'](arg1);
}

export function GetFactorSnapshotStatus() {
  return window['go']['main']['App']['GetFactorSnapshotStatus']();
}

export function GetFactorStoreGovernance(arg1) {
  return window['go']['main']['App']['GetFactorStoreGovernance'](arg1);
}

export function GetPositionHistory() {
  return window['go']['main']['App']['GetPositionHistory']();
}

export function GetPositionHoldings() {
  return window['go']['main']['App']['GetPositionHoldings']();
}

export function GetPositionRecommendation() {
  return window['go']['main']['App']['GetPositionRecommendation']();
}

export function GetPositionSummary() {
  return window['go']['main']['App']['GetPositionSummary']();
}

export function GetProductionDiagnostics() {
  return window['go']['main']['App']['GetProductionDiagnostics']();
}

export function GetProfitArenaMarketDate() {
  return window['go']['main']['App']['GetProfitArenaMarketDate']();
}

export function GetProfitArenaRebalanceStatus() {
  return window['go']['main']['App']['GetProfitArenaRebalanceStatus']();
}

export function GetProfitArenaRunStatus() {
  return window['go']['main']['App']['GetProfitArenaRunStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStockValuation(arg1) {
  return window['go']['main']['App']['GetStockValuation'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function ListDailyBars(arg1) {
  return window['go']['main']['App']['ListDailyBars'](arg1);
}

export function ListDatasetUpdateStatus() {
  return window['go']['main']['App']['ListDatasetUpdateStatus']();
}

export function ListFactorAdmissionComparisons(arg1) {
  return window['go']['main']['App']['ListFactorAdmissionComparisons'](arg1);
}

export function ListFactorCorrelationResults(arg1, arg2) {
  return window['go']['main']['App']['ListFactorCorrelationResults'](arg1, arg2);
}

export function ListFactorICResults(arg1, arg2) {
  return window['go']['main']['App']['ListFactorICResults'](arg1, arg2);
}

export function ListFactorLatestPredictions(arg1, arg2) {
  return window['go']['main']['App']['ListFactorLatestPredictions'](arg1, arg2);
}

export function ListFactorModelFeatures(arg1, arg2) {
  return window['go']['main']['App']['ListFactorModelFeatures'](arg1, arg2);
}

export function ListFactorModelPredictions(arg1, arg2) {
  return window['go']['main']['App']['ListFactorModelPredictions'](arg1, arg2);
}

export function ListFactorObservationEvents(arg1) {
  return window['go']['main']['App']['ListFactorObservationEvents'](arg1);
}

export function ListFactorResearchRuns(arg1) {
  return window['go']['main']['App']['ListFactorResearchRuns'](arg1);
}

export function ListFactorStateICResults(arg1, arg2) {
  return window['go']['main']['App']['ListFactorStateICResults'](arg1, arg2);
}

export function ListFactorStressResults(arg1, arg2) {
  return window['go']['main']['App']['ListFactorStressResults'](arg1, arg2);
}

export function ListFinancialIndicators(arg1) {
  return window['go']['main']['App']['ListFinancialIndicators'](arg1);
}

export function ListMarketDataFiles() {
  return window['go']['main']['App']['ListMarketDataFiles']();
}

export function ListProfitArenaEvaluations(arg1, arg2) {
  return window['go']['main']['App']['ListProfitArenaEvaluations'](arg1, arg2);
}

export function ListProfitArenaFeatures(arg1, arg2) {
  return window['go']['main']['App']['ListProfitArenaFeatures'](arg1, arg2);
}

export function ListProfitArenaPredictions(arg1, arg2) {
  return window['go']['main']['App']['ListProfitArenaPredictions'](arg1, arg2);
}

export function ListProfitArenaRuns(arg1) {
  return window['go']['main']['App']['ListProfitArenaRuns'](arg1);
}

export function ListStockBasic(arg1) {
  return window['go']['main']['App']['ListStockBasic'](arg1);
}

export function ListStrategyScheduleReports() {
  return window['go']['main']['App']['ListStrategyScheduleReports']();
}

export function ListTasks(arg1) {
  return window['go']['main']['App']['ListTasks'](arg1);
}

export function RefreshPositionRealtimeQuotes() {
  return window['go']['main']['App']['RefreshPositionRealtimeQuotes']();
}

export function RefreshTaskStatus(arg1) {
  return window['go']['main']['App']['RefreshTaskStatus'](arg1);
}

export function RetryTask(arg1) {
  return window['go']['main']['App']['RetryTask'](arg1);
}

export function RunDataUpdate(arg1) {
  return window['go']['main']['App']['RunDataUpdate'](arg1);
}

export function RunProfitArenaLatestInference() {
  return window['go']['main']['App']['RunProfitArenaLatestInference']();
}

export function RunProfitArenaTraining() {
  return window['go']['main']['App']['RunProfitArenaTraining']();
}

export function RunStrategyScheduleNow() {
  return window['go']['main']['App']['RunStrategyScheduleNow']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanMarketDataFiles() {
  return window['go']['main']['App']['ScanMarketDataFiles']();
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function TestStrategyScheduleWechat() {
  return window['go']['main']['App']['TestStrategyScheduleWechat']();
}
