// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {task} from '../models';
import {main} from '../models';
import {position} from '../models';
import {datafetch} from '../models';
import {market} from '../models';
import {result} from '../models';
import {config} from '../models';

export function AnalyzePortfolioTask(arg1:string):Promise<task.DTO>;

export function ApplyPortfolioCandidate(arg1:main.ApplyPortfolioCandidateRequest):Promise<main.SettingsResponse>;

export function CancelTask(arg1:string):Promise<task.DTO>;

export function ConfirmPositionTrades(arg1:Array<position.TradeRequest>):Promise<position.Summary>;

export function CreateTask(arg1:task.CreateRequest):Promise<task.DTO>;

export function DeleteTask(arg1:string):Promise<void>;

export function GeneratePositionSignal(arg1:position.GenerateSignalRequest):Promise<position.GenerateSignalResponse>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetDataUpdateStatus():Promise<datafetch.RunStatus>;

export function GetPositionHistory():Promise<Array<position.HistoryPoint>>;

export function GetPositionHoldings():Promise<Array<position.Position>>;

export function GetPositionRecommendation():Promise<position.Recommendation>;

export function GetPositionSummary():Promise<position.Summary>;

export function GetSettings():Promise<main.SettingsResponse>;

export function GetSignalRunStatus():Promise<position.RunStatus>;

export function GetStockValuation(arg1:market.ValuationQuery):Promise<market.StockValuation>;

export function GetTask(arg1:string):Promise<task.DTO>;

export function GetTaskLog(arg1:string,arg2:number):Promise<string>;

export function GetTimeMachineDetail(arg1:string):Promise<result.TimeMachineDetail>;

export function ListDailyBars(arg1:market.DailyQuery):Promise<Array<market.DailyBar>>;

export function ListDataFetchJobs():Promise<Array<main.DataFetchJob>>;

export function ListDatasetUpdateStatus():Promise<Array<datafetch.DatasetStatus>>;

export function ListFinancialIndicators(arg1:market.FinancialQuery):Promise<Array<market.FinancialIndicator>>;

export function ListLimitBreakoutCandidates(arg1:market.BreakoutQuery):Promise<Array<market.LimitBreakoutCandidate>>;

export function ListLimitUpMomentumCandidates(arg1:market.LimitUpMomentumQuery):Promise<Array<market.LimitUpMomentumCandidate>>;

export function ListMarketDataFiles():Promise<Array<market.DataFileDTO>>;

export function ListStockBasic(arg1:market.StockBasicQuery):Promise<Array<market.StockBasic>>;

export function ListTasks(arg1:task.Query):Promise<Array<task.DTO>>;

export function PreviewDataset(arg1:market.DatasetPreviewQuery):Promise<market.DatasetPreview>;

export function RefreshLimitBreakoutCandidates(arg1:market.BreakoutQuery):Promise<Array<market.LimitBreakoutCandidate>>;

export function RefreshLimitUpMomentumCandidates(arg1:market.LimitUpMomentumQuery):Promise<Array<market.LimitUpMomentumCandidate>>;

export function RefreshTaskStatus(arg1:string):Promise<task.DTO>;

export function RunDataUpdate(arg1:datafetch.UpdateRequest):Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<main.SettingsResponse>;

export function ScanMarketDataFiles():Promise<Array<market.DataFileDTO>>;

export function StartTask(arg1:string):Promise<task.DTO>;
