// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateStrategyVersion(arg1) {
  return window['go']['main']['App']['ActivateStrategyVersion'](arg1);
}

export function AnalyzePortfolioTask(arg1) {
  return window['go']['main']['App']['AnalyzePortfolioTask'](arg1);
}

export function ApplyPortfolioCandidate(arg1) {
  return window['go']['main']['App']['ApplyPortfolioCandidate'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function ConfirmPositionTrades(arg1) {
  return window['go']['main']['App']['ConfirmPositionTrades'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GeneratePositionSignal(arg1) {
  return window['go']['main']['App']['GeneratePositionSignal'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDataUpdateStatus() {
  return window['go']['main']['App']['GetDataUpdateStatus']();
}

export function GetPositionHistory() {
  return window['go']['main']['App']['GetPositionHistory']();
}

export function GetPositionHoldings() {
  return window['go']['main']['App']['GetPositionHoldings']();
}

export function GetPositionRecommendation() {
  return window['go']['main']['App']['GetPositionRecommendation']();
}

export function GetPositionSummary() {
  return window['go']['main']['App']['GetPositionSummary']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSignalRunStatus() {
  return window['go']['main']['App']['GetSignalRunStatus']();
}

export function GetStockValuation(arg1) {
  return window['go']['main']['App']['GetStockValuation'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskLog(arg1, arg2) {
  return window['go']['main']['App']['GetTaskLog'](arg1, arg2);
}

export function GetTimeMachineDetail(arg1) {
  return window['go']['main']['App']['GetTimeMachineDetail'](arg1);
}

export function ListDailyBars(arg1) {
  return window['go']['main']['App']['ListDailyBars'](arg1);
}

export function ListDataFetchJobs() {
  return window['go']['main']['App']['ListDataFetchJobs']();
}

export function ListDatasetUpdateStatus() {
  return window['go']['main']['App']['ListDatasetUpdateStatus']();
}

export function ListFinancialIndicators(arg1) {
  return window['go']['main']['App']['ListFinancialIndicators'](arg1);
}

export function ListGovernanceDashboard() {
  return window['go']['main']['App']['ListGovernanceDashboard']();
}

export function ListLimitBreakoutCandidates(arg1) {
  return window['go']['main']['App']['ListLimitBreakoutCandidates'](arg1);
}

export function ListLimitUpMomentumCandidates(arg1) {
  return window['go']['main']['App']['ListLimitUpMomentumCandidates'](arg1);
}

export function ListMarketDataFiles() {
  return window['go']['main']['App']['ListMarketDataFiles']();
}

export function ListRecommendationHindsight() {
  return window['go']['main']['App']['ListRecommendationHindsight']();
}

export function ListStockBasic(arg1) {
  return window['go']['main']['App']['ListStockBasic'](arg1);
}

export function ListStrategyVersions(arg1) {
  return window['go']['main']['App']['ListStrategyVersions'](arg1);
}

export function ListTasks(arg1) {
  return window['go']['main']['App']['ListTasks'](arg1);
}

export function ListValidationEvidence(arg1) {
  return window['go']['main']['App']['ListValidationEvidence'](arg1);
}

export function PreviewDataset(arg1) {
  return window['go']['main']['App']['PreviewDataset'](arg1);
}

export function RefreshGovernanceAudit() {
  return window['go']['main']['App']['RefreshGovernanceAudit']();
}

export function RefreshLimitBreakoutCandidates(arg1) {
  return window['go']['main']['App']['RefreshLimitBreakoutCandidates'](arg1);
}

export function RefreshLimitUpMomentumCandidates(arg1) {
  return window['go']['main']['App']['RefreshLimitUpMomentumCandidates'](arg1);
}

export function RefreshRecommendationHindsight() {
  return window['go']['main']['App']['RefreshRecommendationHindsight']();
}

export function RefreshTaskStatus(arg1) {
  return window['go']['main']['App']['RefreshTaskStatus'](arg1);
}

export function ReviewStrategyVersion(arg1) {
  return window['go']['main']['App']['ReviewStrategyVersion'](arg1);
}

export function RunDataUpdate(arg1) {
  return window['go']['main']['App']['RunDataUpdate'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanMarketDataFiles() {
  return window['go']['main']['App']['ScanMarketDataFiles']();
}

export function SetStrategyVersionStatus(arg1) {
  return window['go']['main']['App']['SetStrategyVersionStatus'](arg1);
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}
