// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateStrategyVersion(arg1) {
  return window['go']['main']['App']['ActivateStrategyVersion'](arg1);
}

export function AnalyzePortfolioTask(arg1) {
  return window['go']['main']['App']['AnalyzePortfolioTask'](arg1);
}

export function ApplyPortfolioCandidate(arg1) {
  return window['go']['main']['App']['ApplyPortfolioCandidate'](arg1);
}

export function CancelPositionSignal() {
  return window['go']['main']['App']['CancelPositionSignal']();
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function ClearLimitBreakoutCandidates() {
  return window['go']['main']['App']['ClearLimitBreakoutCandidates']();
}

export function ClearLimitUpMomentumCandidates() {
  return window['go']['main']['App']['ClearLimitUpMomentumCandidates']();
}

export function ClearPositionPool() {
  return window['go']['main']['App']['ClearPositionPool']();
}

export function ConfirmPositionTrades(arg1) {
  return window['go']['main']['App']['ConfirmPositionTrades'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GeneratePositionSignal(arg1) {
  return window['go']['main']['App']['GeneratePositionSignal'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDataUpdateStatus() {
  return window['go']['main']['App']['GetDataUpdateStatus']();
}

export function GetFactorModelRun(arg1) {
  return window['go']['main']['App']['GetFactorModelRun'](arg1);
}

export function GetLatestPolicySupportSignal() {
  return window['go']['main']['App']['GetLatestPolicySupportSignal']();
}

export function GetLimitBreakoutModelRunStatus() {
  return window['go']['main']['App']['GetLimitBreakoutModelRunStatus']();
}

export function GetLimitBreakoutRunStatus() {
  return window['go']['main']['App']['GetLimitBreakoutRunStatus']();
}

export function GetLimitSignalEvaluationRunStatus() {
  return window['go']['main']['App']['GetLimitSignalEvaluationRunStatus']();
}

export function GetLimitUpModelRunStatus() {
  return window['go']['main']['App']['GetLimitUpModelRunStatus']();
}

export function GetLimitUpMomentumRunStatus() {
  return window['go']['main']['App']['GetLimitUpMomentumRunStatus']();
}

export function GetPolicySupportAnalysisStatus() {
  return window['go']['main']['App']['GetPolicySupportAnalysisStatus']();
}

export function GetPositionHistory() {
  return window['go']['main']['App']['GetPositionHistory']();
}

export function GetPositionHoldings() {
  return window['go']['main']['App']['GetPositionHoldings']();
}

export function GetPositionRecommendation() {
  return window['go']['main']['App']['GetPositionRecommendation']();
}

export function GetPositionSummary() {
  return window['go']['main']['App']['GetPositionSummary']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSignalPortfolioContext() {
  return window['go']['main']['App']['GetSignalPortfolioContext']();
}

export function GetSignalRunStatus() {
  return window['go']['main']['App']['GetSignalRunStatus']();
}

export function GetStockValuation(arg1) {
  return window['go']['main']['App']['GetStockValuation'](arg1);
}

export function GetT0DailyResearchStatus() {
  return window['go']['main']['App']['GetT0DailyResearchStatus']();
}

export function GetT0TimeMachineStatus() {
  return window['go']['main']['App']['GetT0TimeMachineStatus']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetTaskLog(arg1, arg2) {
  return window['go']['main']['App']['GetTaskLog'](arg1, arg2);
}

export function GetTimeMachineDetail(arg1) {
  return window['go']['main']['App']['GetTimeMachineDetail'](arg1);
}

export function ListCrashWarningFeatures(arg1, arg2) {
  return window['go']['main']['App']['ListCrashWarningFeatures'](arg1, arg2);
}

export function ListCrashWarningRuns(arg1) {
  return window['go']['main']['App']['ListCrashWarningRuns'](arg1);
}

export function ListDailyBars(arg1) {
  return window['go']['main']['App']['ListDailyBars'](arg1);
}

export function ListDatasetUpdateStatus() {
  return window['go']['main']['App']['ListDatasetUpdateStatus']();
}

export function ListFactorAdmissionComparisons(arg1) {
  return window['go']['main']['App']['ListFactorAdmissionComparisons'](arg1);
}

export function ListFactorCorrelationResults(arg1, arg2) {
  return window['go']['main']['App']['ListFactorCorrelationResults'](arg1, arg2);
}

export function ListFactorICResults(arg1, arg2) {
  return window['go']['main']['App']['ListFactorICResults'](arg1, arg2);
}

export function ListFactorLatestPredictions(arg1, arg2) {
  return window['go']['main']['App']['ListFactorLatestPredictions'](arg1, arg2);
}

export function ListFactorModelFeatures(arg1, arg2) {
  return window['go']['main']['App']['ListFactorModelFeatures'](arg1, arg2);
}

export function ListFactorModelPredictions(arg1, arg2) {
  return window['go']['main']['App']['ListFactorModelPredictions'](arg1, arg2);
}

export function ListFactorResearchRuns(arg1) {
  return window['go']['main']['App']['ListFactorResearchRuns'](arg1);
}

export function ListFactorStateICResults(arg1, arg2) {
  return window['go']['main']['App']['ListFactorStateICResults'](arg1, arg2);
}

export function ListFactorStressResults(arg1, arg2) {
  return window['go']['main']['App']['ListFactorStressResults'](arg1, arg2);
}

export function ListFinancialIndicators(arg1) {
  return window['go']['main']['App']['ListFinancialIndicators'](arg1);
}

export function ListGovernanceDashboard() {
  return window['go']['main']['App']['ListGovernanceDashboard']();
}

export function ListLimitBreakoutCandidates(arg1) {
  return window['go']['main']['App']['ListLimitBreakoutCandidates'](arg1);
}

export function ListLimitBreakoutModelFeatures(arg1, arg2) {
  return window['go']['main']['App']['ListLimitBreakoutModelFeatures'](arg1, arg2);
}

export function ListLimitBreakoutModelPredictions(arg1, arg2) {
  return window['go']['main']['App']['ListLimitBreakoutModelPredictions'](arg1, arg2);
}

export function ListLimitBreakoutModelRuns(arg1) {
  return window['go']['main']['App']['ListLimitBreakoutModelRuns'](arg1);
}

export function ListLimitBreakoutModelTimeMachineSlices(arg1, arg2) {
  return window['go']['main']['App']['ListLimitBreakoutModelTimeMachineSlices'](arg1, arg2);
}

export function ListLimitSignalEvaluationSummary() {
  return window['go']['main']['App']['ListLimitSignalEvaluationSummary']();
}

export function ListLimitSignalTimeMachineSlices(arg1) {
  return window['go']['main']['App']['ListLimitSignalTimeMachineSlices'](arg1);
}

export function ListLimitUpModelFeatures(arg1, arg2) {
  return window['go']['main']['App']['ListLimitUpModelFeatures'](arg1, arg2);
}

export function ListLimitUpModelPredictions(arg1, arg2) {
  return window['go']['main']['App']['ListLimitUpModelPredictions'](arg1, arg2);
}

export function ListLimitUpModelRuns(arg1) {
  return window['go']['main']['App']['ListLimitUpModelRuns'](arg1);
}

export function ListLimitUpModelTimeMachineSlices(arg1, arg2) {
  return window['go']['main']['App']['ListLimitUpModelTimeMachineSlices'](arg1, arg2);
}

export function ListLimitUpMomentumCandidates(arg1) {
  return window['go']['main']['App']['ListLimitUpMomentumCandidates'](arg1);
}

export function ListMarketDataFiles() {
  return window['go']['main']['App']['ListMarketDataFiles']();
}

export function ListPolicySupportCandidates(arg1) {
  return window['go']['main']['App']['ListPolicySupportCandidates'](arg1);
}

export function ListRecommendationHindsight() {
  return window['go']['main']['App']['ListRecommendationHindsight']();
}

export function ListStockBasic(arg1) {
  return window['go']['main']['App']['ListStockBasic'](arg1);
}

export function ListStrategyVersions(arg1) {
  return window['go']['main']['App']['ListStrategyVersions'](arg1);
}

export function ListT0DailyBacktests(arg1) {
  return window['go']['main']['App']['ListT0DailyBacktests'](arg1);
}

export function ListT0DailyRuns(arg1) {
  return window['go']['main']['App']['ListT0DailyRuns'](arg1);
}

export function ListT0DataPullCandidates(arg1) {
  return window['go']['main']['App']['ListT0DataPullCandidates'](arg1);
}

export function ListT0Recommendations(arg1) {
  return window['go']['main']['App']['ListT0Recommendations'](arg1);
}

export function ListT0TimeMachineResults(arg1) {
  return window['go']['main']['App']['ListT0TimeMachineResults'](arg1);
}

export function ListTasks(arg1) {
  return window['go']['main']['App']['ListTasks'](arg1);
}

export function ListValidationEvidence(arg1) {
  return window['go']['main']['App']['ListValidationEvidence'](arg1);
}

export function RefreshGovernanceAudit() {
  return window['go']['main']['App']['RefreshGovernanceAudit']();
}

export function RefreshLimitBreakoutCandidates(arg1) {
  return window['go']['main']['App']['RefreshLimitBreakoutCandidates'](arg1);
}

export function RefreshLimitUpMomentumCandidates(arg1) {
  return window['go']['main']['App']['RefreshLimitUpMomentumCandidates'](arg1);
}

export function RefreshRecommendationHindsight() {
  return window['go']['main']['App']['RefreshRecommendationHindsight']();
}

export function RefreshTaskStatus(arg1) {
  return window['go']['main']['App']['RefreshTaskStatus'](arg1);
}

export function RetryTask(arg1) {
  return window['go']['main']['App']['RetryTask'](arg1);
}

export function ReviewStrategyVersion(arg1) {
  return window['go']['main']['App']['ReviewStrategyVersion'](arg1);
}

export function RunDataUpdate(arg1) {
  return window['go']['main']['App']['RunDataUpdate'](arg1);
}

export function RunLimitBreakoutModelTraining() {
  return window['go']['main']['App']['RunLimitBreakoutModelTraining']();
}

export function RunLimitSignalEvaluation() {
  return window['go']['main']['App']['RunLimitSignalEvaluation']();
}

export function RunLimitUpModelTraining() {
  return window['go']['main']['App']['RunLimitUpModelTraining']();
}

export function RunPolicySupportAnalysis() {
  return window['go']['main']['App']['RunPolicySupportAnalysis']();
}

export function RunT0DailyResearch() {
  return window['go']['main']['App']['RunT0DailyResearch']();
}

export function RunT0TimeMachine() {
  return window['go']['main']['App']['RunT0TimeMachine']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanMarketDataFiles() {
  return window['go']['main']['App']['ScanMarketDataFiles']();
}

export function SetStrategyVersionStatus(arg1) {
  return window['go']['main']['App']['SetStrategyVersionStatus'](arg1);
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}
