// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {task} from '../models';
import {position} from '../models';
import {datafetch} from '../models';
import {market} from '../models';
import {config} from '../models';

export function ApplyPortfolioCandidate(arg1:main.ApplyPortfolioCandidateRequest):Promise<main.SettingsResponse>;

export function CancelTask(arg1:string):Promise<task.DTO>;

export function CheckExternalDependencies():Promise<Array<main.ExternalDependencyStatus>>;

export function ClearPositionPool():Promise<position.Summary>;

export function ConfirmPositionTrades(arg1:Array<position.TradeRequest>):Promise<position.Summary>;

export function CreateTask(arg1:task.CreateRequest):Promise<task.DTO>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetArenaStrategyDefinitions():Promise<Array<main.ArenaStrategyDefinitionDTO>>;

export function GetDataUpdateStatus():Promise<datafetch.RunStatus>;

export function GetFactorModelRun(arg1:string):Promise<main.FactorModelRun>;

export function GetFactorSnapshotStatus():Promise<position.RunStatus>;

export function GetFactorStoreGovernance(arg1:string):Promise<Record<string, any>>;

export function GetPositionHistory():Promise<Array<position.HistoryPoint>>;

export function GetPositionHoldings():Promise<Array<position.Position>>;

export function GetPositionRecommendation():Promise<position.Recommendation>;

export function GetPositionSummary():Promise<position.Summary>;

export function GetProductionDiagnostics():Promise<Record<string, any>>;

export function GetProfitArenaMarketDate():Promise<string>;

export function GetProfitArenaRebalanceStatus():Promise<position.RunStatus>;

export function GetProfitArenaRunStatus():Promise<position.RunStatus>;

export function GetSettings():Promise<main.SettingsResponse>;

export function GetStockValuation(arg1:market.ValuationQuery):Promise<market.StockValuation>;

export function GetTask(arg1:string):Promise<task.DTO>;

export function ListDailyBars(arg1:market.DailyQuery):Promise<Array<market.DailyBar>>;

export function ListDatasetUpdateStatus():Promise<Array<datafetch.DatasetStatus>>;

export function ListFactorAdmissionComparisons(arg1:number):Promise<Array<main.FactorAdmissionComparison>>;

export function ListFactorCorrelationResults(arg1:string,arg2:number):Promise<Array<main.FactorCorrelationResult>>;

export function ListFactorICResults(arg1:string,arg2:number):Promise<Array<main.FactorICResult>>;

export function ListFactorLatestPredictions(arg1:string,arg2:number):Promise<Array<main.FactorLatestPrediction>>;

export function ListFactorModelFeatures(arg1:string,arg2:number):Promise<Array<main.FactorModelFeature>>;

export function ListFactorModelPredictions(arg1:string,arg2:number):Promise<Array<main.FactorModelPrediction>>;

export function ListFactorObservationEvents(arg1:number):Promise<Array<main.FactorObservationEvent>>;

export function ListFactorResearchRuns(arg1:number):Promise<Array<main.FactorResearchRunSummary>>;

export function ListFactorStateICResults(arg1:string,arg2:number):Promise<Array<main.FactorStateICResult>>;

export function ListFactorStressResults(arg1:string,arg2:number):Promise<Array<main.FactorStressResult>>;

export function ListFinancialIndicators(arg1:market.FinancialQuery):Promise<Array<market.FinancialIndicator>>;

export function ListMarketDataFiles():Promise<Array<market.DataFileDTO>>;

export function ListProfitArenaEvaluations(arg1:string,arg2:number):Promise<Array<main.ProfitArenaEvaluation>>;

export function ListProfitArenaFeatures(arg1:string,arg2:number):Promise<Array<main.ProfitArenaFeature>>;

export function ListProfitArenaPredictions(arg1:string,arg2:number):Promise<Array<main.ProfitArenaPrediction>>;

export function ListProfitArenaRuns(arg1:number):Promise<Array<main.ProfitArenaRunSummary>>;

export function ListStockBasic(arg1:market.StockBasicQuery):Promise<Array<market.StockBasic>>;

export function ListStrategyScheduleReports():Promise<Array<main.StrategyScheduleReport>>;

export function ListTasks(arg1:task.Query):Promise<Array<task.DTO>>;

export function RefreshPositionRealtimeQuotes():Promise<position.Summary>;

export function RefreshTaskStatus(arg1:string):Promise<task.DTO>;

export function RetryTask(arg1:string):Promise<task.DTO>;

export function RunDataUpdate(arg1:datafetch.UpdateRequest):Promise<void>;

export function RunProfitArenaLatestInference():Promise<task.DTO>;

export function RunProfitArenaTraining():Promise<void>;

export function RunStrategyScheduleNow():Promise<main.StrategyScheduleReport>;

export function SaveSettings(arg1:config.Settings):Promise<main.SettingsResponse>;

export function ScanMarketDataFiles():Promise<Array<market.DataFileDTO>>;

export function StartTask(arg1:string):Promise<task.DTO>;

export function TestStrategyScheduleWechat():Promise<main.StrategyScheduleReport>;
